2026.05.25 19:03:51 (workstation)

diff --git a/git.hooks/pre-commit.d/flake8 b/git.hooks/pre-commit.d/flake8
--- a/git.hooks/pre-commit.d/flake8
+++ b/git.hooks/pre-commit.d/flake8
@@ -1,7 +1,9 @@
 #!/bin/sh
 
 echo "Verifying staged Python files with flake8 before commit..."
-
+cd $BASE_DIR
+if [ $? -ne 0 ]; then
+	echo "[ERROR] Unable to change to BASE_DIR '$BASE_DIR'" >&2
 # Verify staged Python files with flake8 before commit.
 
 set -eu
